{
  "name": "EvergreenOS Build",
  "on": {
    "push": {"branches": ["main"]},
    "pull_request": {"branches": ["main"]},
    "workflow_dispatch": {}
  },
  "jobs": {
    "build-artifacts": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {"name": "Checkout", "uses": "actions/checkout@v4"},
        {
          "name": "Set up Python",
          "uses": "actions/setup-python@v5",
          "with": {"python-version": "3.11"}
        },
        {
          "name": "Install build tooling",
          "run": "sudo apt-get update && sudo apt-get install -y qemu-utils xz-utils"
        },
        {
          "name": "Compose rpm-ostree image",
          "run": "python build/scripts/compose.py --manifest configs/manifest.yaml --output artifacts/ostree"
        },
        {
          "name": "Generate installer ISO",
          "run": "python build/scripts/create_iso.py --kickstart build/iso/evergreen.ks --output artifacts/iso && python build/scripts/publish_ostree.py --source artifacts/ostree --destination artifacts/update-repo --version ${{ github.sha }} --gpg-key evergreen-ci"
        },
        {
          "name": "Package QEMU test image",
          "run": "python build/scripts/create_qemu_image.py --ostree artifacts/ostree --output artifacts/qemu"
        },
        {
          "name": "Upload build artifacts",
          "uses": "actions/upload-artifact@v4",
          "with": {
            "name": "evergreenos-artifacts",
            "path": "artifacts"
          }
        }
      ]
    },
    "smoke-test": {
      "runs-on": "ubuntu-latest",
      "needs": "build-artifacts",
      "steps": [
        {"name": "Checkout", "uses": "actions/checkout@v4"},
        {
          "name": "Download build artifacts",
          "uses": "actions/download-artifact@v4",
          "with": {"name": "evergreenos-artifacts", "path": "artifacts"}
        },
        {
          "name": "Boot QEMU smoke test",
          "run": "python build/scripts/qemu_smoke.py --image artifacts/qemu/evergreenos.qcow2 --enroll-url https://ci.test/tenant"
        }
      ]
    }
  }
}
